# k8s/base/api/deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamecloud-api
  labels:
    app: gamecloud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gamecloud-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gamecloud-api
    spec:
      containers:
        - name: gamecloud-api
          image: cr.yandex/crpl3p256m938dtgp3lh/gamecloud.main:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: gamecloud-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: gamecloud-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: gamecloud-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: RABBITMQ_PASSWORD
            - name: ConnectionStrings__GameCloud
              valueFrom:
                secretKeyRef:
                  name: gamecloud-secrets
                  key: DB_CONNECTION_STRING
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10