# k8s/base/api/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamecloud-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: nginx
  rules:
    - host: cloud.playables.studio
      http:
        paths:
          - path: /api
            pathType: Prefix     # Changed to Prefix since you want to match /api/*
            backend:
              service:
                name: gamecloud-api
                port:
                  number: 80