services:
  gamecloud.main:
    image: ${MAIN_IMAGE}:${MAIN_IMAGE_TAG}
    container_name: ${MAIN_CONTAINER_NAME}
    ports:
      - "${MAIN_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__GameCloud=Host=${DB_HOST};Port=${DB_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - gamecloud_network
    depends_on:
      - rabbitmq
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${RABBITMQ_CONTAINER_NAME}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gamecloud_network
    restart: unless-stopped

networks:
  gamecloud_network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  rabbitmq_data:
    name: ${RABBITMQ_VOLUME_NAME}