apiVersion: v1
kind: Secret
metadata:
  name: gamecloud-secrets
  namespace: gamecloud
type: Opaque
stringData:
  RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  DB_CONNECTION_STRING: "Host=${DB_HOST};Port=${DB_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
  VALKEY_CONNECTION_STRING: "${VALKEY_CONNECTION_STRING}"
