apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-config
  namespace: gamecloud
data:
  .env: |
    PORT=8090
    GRPC_SERVER_ADDR=gamecloud-main:5005
    LOG_LEVEL=info
    READ_TIMEOUT=5s
    WRITE_TIMEOUT=10s
    SHUTDOWN_TIME=20s
    GRPC_TIMEOUT=10s
    WS_MAX_MESSAGE_SIZE=32768
    WS_WRITE_WAIT=10s
    WS_PONG_WAIT=60s
    WS_PING_PERIOD=45s
    WS_MAX_MESSAGE_BUFFER=256
    WS_CLOSE_GRACE_PERIOD=10s 