name: CI Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
  YC_REGISTRY: cr.yandex/crpl3p256m938dtgp3lh
  APP_NAME: gamecloud-main
  RELAY_NAME: gamecloud-relay

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive 

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Setup Go
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Main Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ env.YC_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} -f ./Presentation/GameCloud.WebAPI/Dockerfile .

      - name: Build Relay Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ env.YC_REGISTRY }}/${{ env.RELAY_NAME }}:${{ github.sha }} -f ./relay/Dockerfile ./relay